set schema "User";

grant select, create any, update, delete on schema "User" TO "_SYS_REPO" ;

drop table UserDetails ;
CREATE COLUMN TABLE UserDetails (
	 "PERS_NO" 	INTEGER  GENERATED BY DEFAULT AS IDENTITY,
	 "FIRSTNAME" 	NVARCHAR(40),
	 "LASTNAME" 	NVARCHAR(40),
	 "E_MAIL" 	NVARCHAR(255)
) ;

drop type tt_errors ;
CREATE TYPE tt_errors AS TABLE ( 
	 "HTTP_STATUS_CODE" INT ,
	 "ERROR_MESSAGE" 	NVARCHAR(100) ,
	 "DETAIL" 			NVARCHAR(100)  
) ;

-- query result 
select * from UserDetails;

drop procedure prc_1;
create procedure prc_1 as begin
  declare i integer;
 for i in 1 .. 10000 do
insert into UserDetails(firstname, lastname, e_mail) values ('aa', 'aa', 'aaa');
 end for ;
end

call prc_1;

select count(1) from UserDetails ;
delete from UserDetails

